name = "qr-foundry-app"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.production]
name = "qr-foundry-app"
routes = [
  { pattern = "app.qr-foundry.com", custom_domain = true },
]

[env.preview]
name = "qr-foundry-app-preview"

[env.dev]
name = "qr-foundry-app-dev"
